// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AllowedVoter struct {
	MotionID    uuid.UUID `json:"motion_id"`
	HashedEmail string    `json:"hashed_email"`
}

type AnonymousVote struct {
	ID        uuid.UUID          `json:"id"`
	MotionID  uuid.UUID          `json:"motion_id"`
	VoteData  json.RawMessage    `json:"vote_data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Motion struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Questions    []byte             `json:"questions"`
	RequiresTotp pgtype.Bool        `json:"requires_totp"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VoterReceipt struct {
	ID          uuid.UUID          `json:"id"`
	MotionID    uuid.UUID          `json:"motion_id"`
	HashedEmail string             `json:"hashed_email"`
	ReceiptHash string             `json:"receipt_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type VoterRegistry struct {
	HashedEmail string             `json:"hashed_email"`
	IsPresent   pgtype.Bool        `json:"is_present"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
