// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkVoterAllowed = `-- name: CheckVoterAllowed :one
SELECT EXISTS (
    SELECT 1 FROM allowed_voters 
    WHERE motion_id = $1 AND hashed_email = $2
)
`

type CheckVoterAllowedParams struct {
	MotionID    uuid.UUID `json:"motion_id"`
	HashedEmail string    `json:"hashed_email"`
}

func (q *Queries) CheckVoterAllowed(ctx context.Context, arg CheckVoterAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkVoterAllowed, arg.MotionID, arg.HashedEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMotion = `-- name: CreateMotion :one
INSERT INTO motions (title, description, questions, requires_totp, status) 
VALUES ($1, $2, $3, $4, 'PENDING') 
RETURNING id, title, description, questions, requires_totp, status, created_at, updated_at
`

type CreateMotionParams struct {
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Questions    []byte      `json:"questions"`
	RequiresTotp pgtype.Bool `json:"requires_totp"`
}

func (q *Queries) CreateMotion(ctx context.Context, arg CreateMotionParams) (Motion, error) {
	row := q.db.QueryRow(ctx, createMotion,
		arg.Title,
		arg.Description,
		arg.Questions,
		arg.RequiresTotp,
	)
	var i Motion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.RequiresTotp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMotion = `-- name: DeleteMotion :exec
DELETE FROM motions WHERE id = $1
`

func (q *Queries) DeleteMotion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMotion, id)
	return err
}

const getAllMotions = `-- name: GetAllMotions :many
SELECT id, title, description, questions, requires_totp, status, created_at, updated_at FROM motions ORDER BY created_at ASC
`

func (q *Queries) GetAllMotions(ctx context.Context) ([]Motion, error) {
	rows, err := q.db.Query(ctx, getAllMotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Motion
	for rows.Next() {
		var i Motion
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Questions,
			&i.RequiresTotp,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveMotion = `-- name: GetLiveMotion :one
SELECT id, title, description, questions, requires_totp, status, created_at, updated_at FROM motions WHERE status = 'LIVE' LIMIT 1
`

func (q *Queries) GetLiveMotion(ctx context.Context) (Motion, error) {
	row := q.db.QueryRow(ctx, getLiveMotion)
	var i Motion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.RequiresTotp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMotionByID = `-- name: GetMotionByID :one
SELECT id, title, description, questions, requires_totp, status, created_at, updated_at FROM motions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMotionByID(ctx context.Context, id uuid.UUID) (Motion, error) {
	row := q.db.QueryRow(ctx, getMotionByID, id)
	var i Motion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.RequiresTotp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMotionVoteData = `-- name: GetMotionVoteData :many
SELECT vote_data FROM anonymous_votes WHERE motion_id = $1
`

func (q *Queries) GetMotionVoteData(ctx context.Context, motionID uuid.UUID) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, getMotionVoteData, motionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []json.RawMessage
	for rows.Next() {
		var vote_data json.RawMessage
		if err := rows.Scan(&vote_data); err != nil {
			return nil, err
		}
		items = append(items, vote_data)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteCount = `-- name: GetVoteCount :one
SELECT COUNT(*)::int as count FROM anonymous_votes WHERE motion_id = $1
`

func (q *Queries) GetVoteCount(ctx context.Context, motionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getVoteCount, motionID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const hasVoterVoted = `-- name: HasVoterVoted :one
SELECT EXISTS (
    SELECT 1 FROM voter_receipts 
    WHERE motion_id = $1 AND hashed_email = $2
)
`

type HasVoterVotedParams struct {
	MotionID    uuid.UUID `json:"motion_id"`
	HashedEmail string    `json:"hashed_email"`
}

func (q *Queries) HasVoterVoted(ctx context.Context, arg HasVoterVotedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasVoterVoted, arg.MotionID, arg.HashedEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordAnonymousVote = `-- name: RecordAnonymousVote :one
INSERT INTO anonymous_votes (motion_id, vote_data, created_at) 
VALUES ($1, $2, $3) 
RETURNING id, motion_id, vote_data, created_at
`

type RecordAnonymousVoteParams struct {
	MotionID  uuid.UUID          `json:"motion_id"`
	VoteData  json.RawMessage    `json:"vote_data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) RecordAnonymousVote(ctx context.Context, arg RecordAnonymousVoteParams) (AnonymousVote, error) {
	row := q.db.QueryRow(ctx, recordAnonymousVote, arg.MotionID, arg.VoteData, arg.CreatedAt)
	var i AnonymousVote
	err := row.Scan(
		&i.ID,
		&i.MotionID,
		&i.VoteData,
		&i.CreatedAt,
	)
	return i, err
}

const recordVoterReceipt = `-- name: RecordVoterReceipt :one
INSERT INTO voter_receipts (motion_id, hashed_email, receipt_hash) 
VALUES ($1, $2, $3) 
RETURNING id, motion_id, hashed_email, receipt_hash, created_at
`

type RecordVoterReceiptParams struct {
	MotionID    uuid.UUID `json:"motion_id"`
	HashedEmail string    `json:"hashed_email"`
	ReceiptHash string    `json:"receipt_hash"`
}

func (q *Queries) RecordVoterReceipt(ctx context.Context, arg RecordVoterReceiptParams) (VoterReceipt, error) {
	row := q.db.QueryRow(ctx, recordVoterReceipt, arg.MotionID, arg.HashedEmail, arg.ReceiptHash)
	var i VoterReceipt
	err := row.Scan(
		&i.ID,
		&i.MotionID,
		&i.HashedEmail,
		&i.ReceiptHash,
		&i.CreatedAt,
	)
	return i, err
}

const registerVoter = `-- name: RegisterVoter :one
INSERT INTO voter_registry (hashed_email) 
VALUES ($1) 
ON CONFLICT (hashed_email) DO UPDATE SET is_present = EXCLUDED.is_present 
RETURNING hashed_email, is_present, created_at
`

func (q *Queries) RegisterVoter(ctx context.Context, hashedEmail string) (VoterRegistry, error) {
	row := q.db.QueryRow(ctx, registerVoter, hashedEmail)
	var i VoterRegistry
	err := row.Scan(&i.HashedEmail, &i.IsPresent, &i.CreatedAt)
	return i, err
}

const updateMotionContent = `-- name: UpdateMotionContent :one
UPDATE motions 
SET title = $2, description = $3, questions = $4, requires_totp = $5, updated_at = NOW()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, title, description, questions, requires_totp, status, created_at, updated_at
`

type UpdateMotionContentParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Description  pgtype.Text `json:"description"`
	Questions    []byte      `json:"questions"`
	RequiresTotp pgtype.Bool `json:"requires_totp"`
}

func (q *Queries) UpdateMotionContent(ctx context.Context, arg UpdateMotionContentParams) (Motion, error) {
	row := q.db.QueryRow(ctx, updateMotionContent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Questions,
		arg.RequiresTotp,
	)
	var i Motion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.RequiresTotp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMotionStatus = `-- name: UpdateMotionStatus :one
UPDATE motions 
SET status = $2, updated_at = NOW() 
WHERE id = $1 
RETURNING id, title, description, questions, requires_totp, status, created_at, updated_at
`

type UpdateMotionStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateMotionStatus(ctx context.Context, arg UpdateMotionStatusParams) (Motion, error) {
	row := q.db.QueryRow(ctx, updateMotionStatus, arg.ID, arg.Status)
	var i Motion
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.RequiresTotp,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
