// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	CheckVoterAllowed(ctx context.Context, arg CheckVoterAllowedParams) (bool, error)
	CreateMotion(ctx context.Context, arg CreateMotionParams) (Motion, error)
	DeleteMotion(ctx context.Context, id uuid.UUID) error
	GetAllMotions(ctx context.Context) ([]Motion, error)
	GetLiveMotion(ctx context.Context) (Motion, error)
	GetMotionByID(ctx context.Context, id uuid.UUID) (Motion, error)
	GetMotionVoteData(ctx context.Context, motionID uuid.UUID) ([]json.RawMessage, error)
	GetVoteCount(ctx context.Context, motionID uuid.UUID) (int32, error)
	HasVoterVoted(ctx context.Context, arg HasVoterVotedParams) (bool, error)
	RecordAnonymousVote(ctx context.Context, arg RecordAnonymousVoteParams) (AnonymousVote, error)
	RecordVoterReceipt(ctx context.Context, arg RecordVoterReceiptParams) (VoterReceipt, error)
	RegisterVoter(ctx context.Context, hashedEmail string) (VoterRegistry, error)
	UpdateMotionContent(ctx context.Context, arg UpdateMotionContentParams) (Motion, error)
	UpdateMotionStatus(ctx context.Context, arg UpdateMotionStatusParams) (Motion, error)
}

var _ Querier = (*Queries)(nil)
